/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

let _deepseek_ai_dsh_experimental_agent_team_presets_teamPresets_catalog_result$schema$value
const _deepseek_ai_dsh_experimental_agent_team_presets_teamPresets_catalog_result$schema = () => (_deepseek_ai_dsh_experimental_agent_team_presets_teamPresets_catalog_result$schema$value ??= z.object({
  'tools': z.array(z.object({
  'name': z.string(),
  'description': z.string(),
})),
}))

export const TYPERT = {
  package: 'dsh-agent-team-presets',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: 'dsh-agent-team-presets#teamPresets/catalog',
      service: 'teamPresetsToolCatalog',
      namespace: 'teamPresets',
      method: 'catalog',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-agent-team-presets/types#ToolCatalogValue',
        create: _deepseek_ai_dsh_experimental_agent_team_presets_teamPresets_catalog_result$schema,
      },
      sourceLocation: {"file":"packages/experimental/agent-team-presets/src/tool-catalog.ts","line":43,"column":3},
    },
  ],
  model: {
    "services": [],
    "events": [],
    "objects": []
  },
}
