/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { ToolCatalogValue } from 'dsh-agent-team-presets/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$7465616d50726573657473 {
    catalog: () => Promise<RemoteResult<ToolCatalogValue>>
  }
  interface TypertRemoteMap {
    'teamPresets/catalog': () => Promise<RemoteResult<ToolCatalogValue>>
  }
  interface TypertRemoteNamespaceMap {
    'teamPresets': TypertRemoteNamespace$7465616d50726573657473
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
